PREVENT-AD open v20.1 - implement BIDS API endpoints
cmadjar/Loris pull request #8
Opened 2020-05-04 21:23 UTC by cmadjar

This PR shows the changes needed to add BIDS endpoints to the LORIS API of the open PREVENT-AD instance that is running v20.1 of LORIS.

2020-05-07 14:26 UTC, xlecours requested changes
Petites suggestions
Je suis rendu à htdocs/api/v0.0.3-dev/candidates/visits/images/bidsfiles/BidsFile.php

2020-05-07 14:26 UTC, xlecours commented on BIDS_endpoints_proposal.md
> +  "BidsFiles": {
Je placerais BidsFiles sous {visit}/bidsfiles. Dans l'API actuel, il y a déjà `instruments`, `qc`, `recordings`, `images` et `dicoms` et leurs infos sont disponible dans leur endpoints et non sour /{visit}

2020-05-07 14:26 UTC, xlecours commented on htdocs/api/v0.0.3-dev/.htaccess
> +RewriteRule ^candidates/([0-9]+)/([a-zA-Z0-9_.]+)/bidsfiles$ candidates/visits/BidsFiles.php?CandID=$1&VisitLabel=$2&PrintFiles=true [L]
Ceci correspond à mon commentaire du point #3 dans le proposal.

2020-05-07 14:26 UTC, xlecours commented on htdocs/api/v0.0.3-dev/candidates/Visit.php
> +
tel que mentionné, je metterais ça dans `candidates/visits/BidsFiles.php`

2020-05-07 15:27 UTC, xlecours commented
Le reste semble correct. Comme ce sont de nouveaux fichier, il n'y a pas de mal à les intégrer puis ajuster si les outputs sont un peu croche. Idéalement j'aimerais tester mais ce n'est pas si simple d'avoir une vm avec la bonne version de LORIS et des données de test. Si tu veux, je pourrais ajouter quelques endpoints au Jupyter Notebook.

2020-05-08 12:57 UTC, cmadjar commented
Un gros merci @xlecours !! J'ai fait les changements requis. Je vais faire le merge et mettre ça sur production. Ce sera plus facile pour tester les endpoints. Je pensais continuer sur ma lancé et modifier ajouter à LAMID la possibilité de downloader PREVENT-AD en BIDS :). Comme je suis dedans, je vais commencer à jouer un peu. Je te demanderai surement de jeter un coup d'oeil à mes modifs si tu as le temps.

Merci beaucoup pour ton aide très apprécié !! :-D

2020-05-08 12:57 UTC, merged

2020-05-08 19:03 UTC, xlecours commented
Fantastique !

On Fri, May 8, 2020 at 8:57 AM cmadjar <notifications@github.com> wrote:

> Merged #8 <https://github.com/cmadjar/Loris/pull/8> into
> PreventAD-open_v20.1.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmadjar/Loris/pull/8#event-3316855703>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC4XSTXB2D6L6LVZIVAOANTRQP6VLANCNFSM4MZDBFQA>
> .
>